spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javalib?serverTimezone=Asia/Shanghai
    username: forJava
    password: 123456

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
